### ISSUE TITLE
Writing an elixir thrift client. How do you choose the protocol?

### ISSUE THREAD

**Issue by fire** [pinterest/riffed#14]
Trying to connect to an existing server in java. How do you select the protocol? The server appears to be using the cp protocol, but in the future the client library can be ssl too.

**Comment by fire** [comment]
I was able to connect using the Binary Protocol and no framing. However I wish to support ssl.

**Comment by scohen** [comment]
When you call `ClientModule.connect(host, port)`, that should pass the client_options that you defined into `thrift_client_util.new`. 

from https://github.com/apache/thrift/blob/master/lib/erl/src/thrift_client_util.erl#L46, you should be able to add  `ssltransport: true` to your client_opts, which should enable ssl. You do the same thing (`framed: true`) to enable framing.

**Comment by fire** [comment]
Actually, do you know where the compact protocol will be supported? It seems to require a pre-release.

**Comment by scohen** [comment]
Looks like master has an option for compact, but it's not in 0.9.3. My guess is that it'll be in the next release (I don't know when that will be), which will affect riffed as well, and make it much easier to build clients and servers. 

With the exception of compact, did this work for you?

**Comment by scohen** [comment]
Oh, would you like me to update the docs to show how to choose protocols?

**Comment by fire** [comment]
I was able to test binary protocol and framed is false, but not sure about ssl. 

Do you know if the server is compatible with letsencrypt? Also, does elixir use the default linux / windows certificate authority list?

**Comment by scohen** [comment]
We use framed binary, and interoperate with a bunch of other languages, so I'm positive they work. Our configs look like this:
```elixir
  client_opts: [
    framed: true,
    retries: 3
  ]
```
That'll give you binary + framed. 

We don't use letsencrypt, so I don't know about that. You can add keys to the erlang application, which you might need to do to get it working. Details here: http://erlang.org/doc/man/ssl.html

You can also ask on the elixir-lang IRC channel on Freenode. They're extremely helpful with this kind of thing.

**Comment by scohen** [comment]
@fire, does that help?

**Comment by fire** [comment]
Yes, but I need more work on the ssl.

**Comment by scohen** [comment]
Closing, as this is more of a thrift implementation issue (and we talked in IRC)
