### ISSUE TITLE
Please consider making riffed available as a package on hex.pm

### ISSUE THREAD

**Issue by adrienmo** [pinterest/riffed#30]
Please consider making riffed available as a package on hex.pm, so other hex packages can refer to this project as a dependency :) 

On another topic, please also consider removing exlager from the lib dependencies, so using this library does not force you to use it.

Thanks!

**Comment by scohen** [comment]
Sadly, I don't think we can because of the way we use `elixir-thrift`. It needs to pull in the apache source code, which isn't available on hex. 

I'll look into it, but we had a similar problem with elixometer.

**Comment by jparise** [comment]
[elixir-thrift](https://hex.pm/packages/thrift) is available on Hex and includes a copy of the required Apache Thrift runtime files. That should provide all of the necessary build and runtime dependencies for Riffed.

**Comment by scohen** [comment]
I'll give it a shot.
