### ISSUE TITLE
Use of binary_protocol

### ISSUE THREAD

**Issue by MeerKatDev** [pinterest/riffed#56]
How do I deserialize a binary_message, like a simple function call? (e.g. add(1,1))
I can't seem to find the right usage of the` :thrift_protocol.read` function

**Comment by scohen** [comment]
Any reason you're using riffed rather than https://github.com/pinterest/elixir-thrift? 
That library allows you to deserialize messages much more easily; riffed piggybacks off of the erlang thrift implementation, which makes this kind of operation pretty difficult.
